# Generated by Django 5.1.6 on 2025-02-12 14:02

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.ForeignKey(
                default=accounts.models.Role.get_default_role_pk,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.role",
            ),
        ),
    ]
