# Generated by Django 5.1.6 on 2025-02-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_follow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="following",
            new_name="followed",
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "followed")},
        ),
    ]
