# Generated by Django 5.1.6 on 2025-02-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_bookmark"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmark",
            options={"verbose_name_plural": "Bookmarks"},
        ),
    ]
