# Generated by Django 5.1.6 on 2025-02-19 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("READ", "Read"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("LOGIN_FAIL", "Login Failed"),
                            ("LIKE", "Like"),
                            ("UN_LIKE", "Un Like"),
                            ("FOLLOW", "Follow"),
                            ("UN_FOLLOW", "Un Follow"),
                            ("BOOKMARK", "Bookmark"),
                            ("UN_BOOKMARK", "Un bookmark"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_time", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("SUCC", "Success"), ("FAIL", "Failed")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-action_time",),
                "indexes": [
                    models.Index(
                        fields=["user"], name="activity_lo_user_id_6e217e_idx"
                    ),
                    models.Index(
                        fields=["action_type"], name="activity_lo_action__220821_idx"
                    ),
                ],
            },
        ),
    ]
