# Generated by Django 5.1.6 on 2025-02-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_log", "0002_alter_activitylog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("READ", "Read"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("LOGIN_FAIL", "Login Failed"),
                    ("LIKE", "Like"),
                    ("UN_LIKE", "Un Like"),
                    ("FOLLOW", "Follow"),
                    ("UN_FOLLOW", "Un Follow"),
                    ("BOOKMARK", "Bookmark"),
                    ("UN_BOOKMARK", "Un bookmark"),
                    ("COMMENT", "Comment"),
                ],
                max_length=20,
            ),
        ),
    ]
