# Generated by Django 5.1.6 on 2025-02-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
