# Generated by Django 5.1.6 on 2025-02-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_is_read"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ("-creation_time",)},
        ),
    ]
